# Generated by Django 5.0.2 on 2024-02-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todos",
        ),
    ]
