# Generated by Django 5.0.1 on 2024-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
