# Generated by Django 5.0.1 on 2024-02-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_due_date_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
