# Generated by Django 5.0.1 on 2024-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todo_due_date_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
